// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{

	public class Location{
		public string name{ get; set;}
		public float longitude{ get; set; }
		public float latitude{ get; set; }
		public float height{ get; set; }
		public Location(string name,float lon,float lat,float h){
			this.name = name;
			longitude = lon;
			latitude = lat;
			height = h;
		}
		public Location(string name,float lon, float lat){
			this.name = name;
			longitude = lon;
			latitude = lat;
			height = -11111f;
		}
		public Location(float lon,float lat,float h){
			name = null;
			longitude = lon;
			latitude = lat;
			height = h;
		}

		public Location(float lon, float lat){
			name = null;
			longitude = lon;
			latitude = lat;
			height = -11111f;
		}

		public static Location operator +(Location a, Location b){
			if (a.height == -11111f || b.height == -11111f) {
				return new Location (a.name, a.longitude + b.longitude, a.latitude + b.latitude, -11111f);
						}
			else{
				return new Location (a.name, a.longitude + b.longitude, a.latitude + b.latitude, a.height + b.height);
			}
		}
	}
}

